import { useCallback, useEffect, useState } from "react";
import { Archive, FileText, Pencil, Plus, RefreshCw } from "lucide-react";
import API, { assetUrl } from "../api/axios";
import { Badge, Button, Card, ConfirmDialog, EmptyState, Field, Input, LoadingState, Modal, PageHeader, Textarea, Toggle } from "../components/ui";
import { useToast } from "../context/ToastContext";
import { dateTime } from "../utils/format";
import { getErrorMessage } from "../utils/errors";
import { validateImageFiles } from "../utils/validation";
import { useObjectUrl } from "../hooks/useObjectUrl";
const blank = { title: "", slug: "", excerpt: "", content: "", author: "legendbornnutrition", tags: "", isPublished: false, media: null };
export default function Articles() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState(""); const [form, setForm] = useState(blank); const [existingImage, setExistingImage] = useState(""); const [saving, setSaving] = useState(false); const [archiveTarget, setArchiveTarget] = useState(null); const toast = useToast();
  const load = useCallback(async () => { try { setLoading(true); const { data } = await API.get("/blogs/admin/all"); setItems(data.data || []); } catch (error) { toast.error(getErrorMessage(error, "Articles could not be loaded.")); } finally { setLoading(false); } }, [toast]); useEffect(() => { load(); }, [load]);
  const openCreate = () => { setEditingId(""); setForm(blank); setExistingImage(""); setEditorOpen(true); }; const openEdit = (item) => { setEditingId(item._id); setExistingImage(item.coverImage || ""); setForm({ title: item.title || "", slug: item.slug || "", excerpt: item.excerpt || "", content: item.content || "", author: item.author || "legendbornnutrition", tags: (item.tags || []).join(", "), isPublished: item.isPublished === true, media: null }); setEditorOpen(true); };
  const submit = async () => {
    if (!form.title.trim() || form.content.trim().length < 50) { toast.error("Article title and at least 50 characters of meaningful content are required."); return; }
    if (form.title.trim().length > 140) { toast.error("Article title must be 140 characters or fewer."); return; }
    if (form.excerpt.trim().length > 400) { toast.error("Article excerpt must be 400 characters or fewer."); return; }
    const imageError = validateImageFiles(form.media ? [form.media] : [], { maxFiles: 1 });
    if (imageError) { toast.error(imageError); return; }
    try { setSaving(true); const fd = new FormData(); Object.entries({ ...form, title: form.title.trim(), slug: form.slug.trim(), excerpt: form.excerpt.trim(), content: form.content.trim(), author: form.author.trim() || "legendbornnutrition" }).forEach(([key, value]) => { if (key === "media") { if (value) fd.append("media", value); } else fd.append(key, String(value)); }); const { data } = editingId ? await API.put(`/blogs/${editingId}`, fd) : await API.post("/blogs", fd); setItems((current) => editingId ? current.map((item) => item._id === editingId ? data.data : item) : [data.data, ...current]); toast.success(data.message || "Article saved."); setEditorOpen(false); } catch (error) { toast.error(getErrorMessage(error, "Article could not be saved.")); } finally { setSaving(false); }
  };
  const archive = async () => { if (!archiveTarget) return; try { setSaving(true); const { data } = await API.delete(`/blogs/${archiveTarget._id}`); setItems((current) => current.map((item) => item._id === archiveTarget._id ? { ...item, isPublished: false } : item)); toast.success(data.message || "Article unpublished."); setArchiveTarget(null); } catch (error) { toast.error(getErrorMessage(error)); } finally { setSaving(false); } };
  const selectedPreview = useObjectUrl(form.media);
  const preview = selectedPreview || (existingImage ? assetUrl(existingImage) : "");
  return <div className="space-y-6"><PageHeader eyebrow="Optional educational content" title="Articles" description="The backend supports articles, but the current customer frontend does not expose blog routes. Publish here only after adding matching storefront pages and navigation." actions={<><Button variant="secondary" onClick={load}><RefreshCw size={17} /> Refresh</Button><Button onClick={openCreate}><Plus size={17} /> Add article</Button></>} />
    <Card className="border-amber-200 bg-amber-50 p-4 shadow-none"><p className="text-sm leading-6 text-amber-950"><strong>Compatibility note:</strong> articles are stored by the server but are not currently visible in the latest storefront build. This page is retained for future content expansion.</p></Card>
    <Card className="overflow-hidden">{loading ? <LoadingState label="Loading articles…" /> : items.length ? <div className="divide-y divide-stone-100">{items.map((item) => <article key={item._id} className="grid gap-4 p-5 md:grid-cols-[120px_1fr_auto]"><div className="h-24 overflow-hidden rounded-xl border bg-stone-100">{item.coverImage ? <img src={assetUrl(item.coverImage)} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-stone-400"><FileText size={24} /></div>}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-stone-950">{item.title}</h2><Badge tone={item.isPublished ? "success" : "neutral"}>{item.isPublished ? "Published" : "Draft"}</Badge></div><p className="mt-1 line-clamp-2 text-sm leading-6 text-stone-600">{item.excerpt || item.content}</p><p className="mt-2 text-xs text-stone-500">{item.author} · {dateTime(item.publishedAt || item.createdAt)} · /{item.slug}</p></div><div className="flex items-start gap-2"><Button size="sm" variant="secondary" onClick={() => openEdit(item)}><Pencil size={15} /> Edit</Button>{item.isPublished && <Button size="sm" variant="danger" onClick={() => setArchiveTarget(item)}><Archive size={15} /></Button>}</div></article>)}</div> : <EmptyState icon={FileText} title="No articles" description="Articles are optional and currently not surfaced by the customer frontend." />}</Card>
    <Modal open={editorOpen} onClose={() => setEditorOpen(false)} title={editingId ? "Edit article" : "Add article"} size="xl" footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditorOpen(false)}>Cancel</Button><Button onClick={submit} disabled={saving}>{saving ? "Saving…" : "Save article"}</Button></div>}><div className="grid gap-5 md:grid-cols-2"><Field label="Title" required><Input value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></Field><Field label="Slug"><Input value={form.slug} onChange={(event) => setForm((current) => ({ ...current, slug: event.target.value }))} /></Field><Field label="Author"><Input value={form.author} onChange={(event) => setForm((current) => ({ ...current, author: event.target.value }))} /></Field><Field label="Tags" hint="Comma separated"><Input value={form.tags} onChange={(event) => setForm((current) => ({ ...current, tags: event.target.value }))} /></Field><Field label="Excerpt" className="md:col-span-2"><Textarea rows="3" maxLength="400" value={form.excerpt} onChange={(event) => setForm((current) => ({ ...current, excerpt: event.target.value }))} /></Field><Field label="Article content" required className="md:col-span-2"><Textarea rows="14" value={form.content} onChange={(event) => setForm((current) => ({ ...current, content: event.target.value }))} /></Field><Field label="Cover image"><Input type="file" accept="image/*" onChange={(event) => setForm((current) => ({ ...current, media: event.target.files?.[0] || null }))} /></Field>{preview && <img src={preview} alt="Preview" className="h-32 w-full rounded-xl border object-cover" />}<Toggle checked={form.isPublished} onChange={(value) => setForm((current) => ({ ...current, isPublished: value }))} label="Publish article" /></div></Modal><ConfirmDialog open={Boolean(archiveTarget)} onClose={() => setArchiveTarget(null)} onConfirm={archive} loading={saving} dangerous title="Unpublish article" confirmLabel="Unpublish" description={`Unpublish ${archiveTarget?.title}?`} />
  </div>;
}
