import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, FolderTree, Pencil, Plus, RefreshCw, Search } from "lucide-react";
import API, { assetUrl } from "../api/axios";
import { Badge, Button, Card, ConfirmDialog, EmptyState, Field, Input, LoadingState, Modal, PageHeader, Textarea, Toggle } from "../components/ui";
import { useToast } from "../context/ToastContext";
import { getErrorMessage } from "../utils/errors";
import { validateImageFiles } from "../utils/validation";
import { useObjectUrl } from "../hooks/useObjectUrl";

const blank = { name: "", slug: "", description: "", isActive: true, image: null };
export default function Categories() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState(""); const [form, setForm] = useState(blank); const [existingImage, setExistingImage] = useState(""); const [saving, setSaving] = useState(false); const [archiveTarget, setArchiveTarget] = useState(null); const toast = useToast();
  const load = useCallback(async () => { try { setLoading(true); const { data } = await API.get("/categories/admin/all"); setItems(data.data || []); } catch (error) { toast.error(getErrorMessage(error, "Categories could not be loaded.")); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const keyword = search.trim().toLowerCase(); return items.filter((item) => !keyword || [item.name, item.slug, item.description].some((value) => String(value || "").toLowerCase().includes(keyword))); }, [items, search]);
  const openCreate = () => { setEditingId(""); setForm(blank); setExistingImage(""); setEditorOpen(true); };
  const openEdit = (item) => { setEditingId(item._id); setForm({ name: item.name || "", slug: item.slug || "", description: item.description || "", isActive: item.isActive !== false, image: null }); setExistingImage(item.image || ""); setEditorOpen(true); };
  const submit = async () => {
    if (!form.name.trim()) { toast.error("Category name is required."); return; }
    if (form.name.trim().length > 80) { toast.error("Category name must be 80 characters or fewer."); return; }
    if (form.description.trim().length > 500) { toast.error("Category description must be 500 characters or fewer."); return; }
    const imageError = validateImageFiles(form.image ? [form.image] : [], { maxFiles: 1 });
    if (imageError) { toast.error(imageError); return; }
    try { setSaving(true); const fd = new FormData(); fd.append("name", form.name.trim()); fd.append("slug", form.slug.trim()); fd.append("description", form.description.trim()); fd.append("isActive", String(form.isActive)); if (form.image) fd.append("image", form.image); const { data } = editingId ? await API.put(`/categories/${editingId}`, fd) : await API.post("/categories", fd); setItems((current) => editingId ? current.map((item) => item._id === editingId ? data.data : item) : [...current, data.data].sort((a, b) => a.name.localeCompare(b.name))); toast.success(data.message || "Category saved."); setEditorOpen(false); } catch (error) { toast.error(getErrorMessage(error, "Category could not be saved.")); } finally { setSaving(false); }
  };
  const archive = async () => { if (!archiveTarget) return; try { setSaving(true); const { data } = await API.delete(`/categories/${archiveTarget._id}`); setItems((current) => current.map((item) => item._id === archiveTarget._id ? { ...item, isActive: false } : item)); toast.success(data.message || "Category archived."); setArchiveTarget(null); } catch (error) { toast.error(getErrorMessage(error, "Category could not be archived. Move or archive active products first.")); } finally { setSaving(false); } };
  const selectedPreview = useObjectUrl(form.image);
  const preview = selectedPreview || (existingImage ? assetUrl(existingImage) : "");
  return <div className="space-y-6"><PageHeader eyebrow="Catalogue structure" title="Categories" description="Categories power storefront navigation and product filtering. Archive only after all active products have been moved or hidden." actions={<><Button variant="secondary" onClick={load}><RefreshCw size={17} /> Refresh</Button><Button onClick={openCreate}><Plus size={17} /> Add category</Button></>} />
    <Card className="overflow-hidden"><div className="border-b border-stone-200 p-4"><div className="relative max-w-md"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-400" /><Input className="pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search categories" /></div></div>{loading ? <LoadingState label="Loading categories…" /> : visible.length ? <div className="grid gap-0 md:grid-cols-2 xl:grid-cols-3">{visible.map((item) => <article key={item._id} className="border-b border-stone-100 p-5 md:border-r"><div className="flex gap-4"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl border border-stone-200 bg-stone-100">{item.image ? <img src={assetUrl(item.image)} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-stone-400"><FolderTree size={24} /></div>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h2 className="truncate font-bold text-stone-950">{item.name}</h2><p className="text-xs text-stone-500">/{item.slug}</p></div><Badge tone={item.isActive !== false ? "success" : "neutral"}>{item.isActive !== false ? "Active" : "Inactive"}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-stone-600">{item.description || "No category description"}</p></div></div><div className="mt-4 flex justify-end gap-2"><Button size="sm" variant="secondary" onClick={() => openEdit(item)}><Pencil size={15} /> Edit</Button>{item.isActive !== false && <Button size="sm" variant="danger" onClick={() => setArchiveTarget(item)}><Archive size={15} /></Button>}</div></article>)}</div> : <EmptyState icon={FolderTree} title="No categories found" action={<Button onClick={openCreate}><Plus size={17} /> Add category</Button>} />}</Card>
    <Modal open={editorOpen} onClose={() => setEditorOpen(false)} title={editingId ? "Edit category" : "Add category"} size="md" footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditorOpen(false)}>Cancel</Button><Button onClick={submit} disabled={saving}>{saving ? "Saving…" : "Save category"}</Button></div>}><div className="grid gap-5"><Field label="Category name" required><Input value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></Field><Field label="Slug" hint="Leave blank when creating to derive it from the name."><Input value={form.slug} onChange={(event) => setForm((current) => ({ ...current, slug: event.target.value }))} /></Field><Field label="Description"><Textarea rows="4" maxLength="500" value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></Field><Field label="Category image"><Input type="file" accept="image/*" onChange={(event) => setForm((current) => ({ ...current, image: event.target.files?.[0] || null }))} /></Field>{preview && <img src={preview} alt="Category preview" className="h-40 w-full rounded-xl border border-stone-200 object-cover" />}<Toggle checked={form.isActive} onChange={(value) => setForm((current) => ({ ...current, isActive: value }))} label="Category visible" description="The storefront only shows active categories." /></div></Modal>
    <ConfirmDialog open={Boolean(archiveTarget)} onClose={() => setArchiveTarget(null)} onConfirm={archive} loading={saving} dangerous title="Archive category" confirmLabel="Archive category" description={`Archive ${archiveTarget?.name}? The server will reject this action if active products still belong to it.`} />
  </div>;
}
