import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Image, RefreshCw, Search, Star, Trash2, XCircle } from "lucide-react";
import API, { assetUrl } from "../api/axios";
import { Badge, Button, Card, ConfirmDialog, EmptyState, Input, LoadingState, PageHeader } from "../components/ui";
import { useToast } from "../context/ToastContext";
import { dateTime } from "../utils/format";
import { getErrorMessage } from "../utils/errors";

export default function Reviews() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("PENDING"); const [savingId, setSavingId] = useState(""); const [deleteTarget, setDeleteTarget] = useState(null); const toast = useToast();
  const load = useCallback(async () => { try { setLoading(true); const { data } = await API.get("/products/admin/all?limit=all"); setProducts(data.data || []); } catch (error) { toast.error(getErrorMessage(error, "Product reviews could not be loaded.")); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const reviews = useMemo(() => products.flatMap((product) => (product.reviews || []).map((review) => ({ ...review, productName: product.name, productSlug: product.slug }))).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [products]);
  const visible = useMemo(() => { const keyword = search.trim().toLowerCase(); return reviews.filter((review) => (filter === "ALL" || filter === "PENDING" && !review.isApproved || filter === "APPROVED" && review.isApproved || filter === "VERIFIED" && review.isVerifiedPurchase) && (!keyword || [review.name, review.email, review.productName, review.comment].some((value) => String(value || "").toLowerCase().includes(keyword)))); }, [reviews, filter, search]);
  const toggle = async (review) => { try { setSavingId(review._id); const { data } = await API.patch(`/products/${review.productSlug}/reviews/${review._id}/status`, { isApproved: !review.isApproved }); toast.success(data.message || "Review status updated."); await load(); } catch (error) { toast.error(getErrorMessage(error, "Review status could not be updated.")); } finally { setSavingId(""); } };
  const remove = async () => { if (!deleteTarget) return; try { setSavingId(deleteTarget._id); const { data } = await API.delete(`/products/${deleteTarget.productSlug}/reviews/${deleteTarget._id}`); toast.success(data.message || "Review deleted."); setDeleteTarget(null); await load(); } catch (error) { toast.error(getErrorMessage(error, "Review could not be deleted.")); } finally { setSavingId(""); } };
  return <div className="space-y-6"><PageHeader eyebrow="Customer content moderation" title="Product reviews" description="Approve only genuine, appropriate reviews. Verified purchase status comes from eligible completed customer orders on the backend." actions={<Button variant="secondary" onClick={load}><RefreshCw size={17} /> Refresh</Button>} />
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-stone-200 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="relative max-w-md flex-1"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-400" /><Input className="pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reviewer, product or comment" /></div><div className="flex gap-2">{[["PENDING", "Pending"], ["APPROVED", "Approved"], ["VERIFIED", "Verified"], ["ALL", "All"]].map(([value, label]) => <button key={value} type="button" onClick={() => setFilter(value)} className={`rounded-xl px-3 py-2 text-xs font-bold ${filter === value ? "bg-brand-800 text-white" : "border border-stone-200 bg-white text-stone-600"}`}>{label}</button>)}</div></div>
      {loading ? <LoadingState label="Loading reviews…" /> : visible.length ? <div className="divide-y divide-stone-100">{visible.map((review) => <article key={review._id} className="grid gap-4 p-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-stone-950">{review.productName}</h2><Badge tone={review.isApproved ? "success" : "warning"}>{review.isApproved ? "Approved" : "Pending"}</Badge>{review.isVerifiedPurchase && <Badge tone="info">Verified purchase</Badge>}</div><div className="mt-2 flex items-center gap-1 text-gold-500">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={15} fill={index < Number(review.rating || 0) ? "currentColor" : "none"} />)}</div><p className="mt-3 text-sm leading-6 text-stone-700">{review.comment}</p><p className="mt-3 text-xs text-stone-500">{review.name} · {review.email || "No public email"} · {dateTime(review.createdAt)}</p>{review.media?.length > 0 && <div className="mt-3 flex gap-2">{review.media.map((media) => media.type === "image" ? <img key={media.url} src={assetUrl(media.url)} alt="Review attachment" className="h-16 w-16 rounded-lg border object-cover" /> : <a key={media.url} className="btn btn-secondary btn-sm" href={assetUrl(media.url)} target="_blank" rel="noreferrer"><Image size={15} /> Media</a>)}</div>}</div><div className="flex items-start gap-2"><Button size="sm" variant={review.isApproved ? "secondary" : "primary"} disabled={savingId === review._id} onClick={() => toggle(review)}>{review.isApproved ? <XCircle size={15} /> : <CheckCircle2 size={15} />}{review.isApproved ? "Unapprove" : "Approve"}</Button><Button size="sm" variant="danger" onClick={() => setDeleteTarget(review)}><Trash2 size={15} /></Button></div></article>)}</div> : <EmptyState icon={Star} title="No reviews in this view" description="Customer reviews will appear here after submission." />}
    </Card><ConfirmDialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} onConfirm={remove} loading={Boolean(savingId)} dangerous title="Delete review" confirmLabel="Delete review" description={`Permanently delete the review submitted by ${deleteTarget?.name || "this customer"}? This cannot be restored from the admin.`} />
  </div>;
}
