import { useCallback, useEffect, useState } from "react";
import { Archive, Pencil, Plus, Quote, RefreshCw, Star } from "lucide-react";
import API, { assetUrl } from "../api/axios";
import { Badge, Button, Card, ConfirmDialog, EmptyState, Field, Input, LoadingState, Modal, PageHeader, Textarea, Toggle } from "../components/ui";
import { useToast } from "../context/ToastContext";
import { getErrorMessage } from "../utils/errors";
import { isWholeNumber, validateImageFiles } from "../utils/validation";
import { useObjectUrl } from "../hooks/useObjectUrl";
const blank = { name: "", location: "", rating: "5", text: "", isActive: true, sortOrder: "0", media: null };
export default function Testimonials() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState(""); const [form, setForm] = useState(blank); const [existingImage, setExistingImage] = useState(""); const [saving, setSaving] = useState(false); const [archiveTarget, setArchiveTarget] = useState(null); const toast = useToast();
  const load = useCallback(async () => { try { setLoading(true); const { data } = await API.get("/testimonials/admin/all"); setItems(data.data || []); } catch (error) { toast.error(getErrorMessage(error, "Testimonials could not be loaded.")); } finally { setLoading(false); } }, [toast]); useEffect(() => { load(); }, [load]);
  const openCreate = () => { setEditingId(""); setForm(blank); setExistingImage(""); setEditorOpen(true); }; const openEdit = (item) => { setEditingId(item._id); setExistingImage(item.image || ""); setForm({ name: item.name || "", location: item.location || "", rating: String(item.rating || 5), text: item.text || "", isActive: item.isActive !== false, sortOrder: String(item.sortOrder || 0), media: null }); setEditorOpen(true); };
  const submit = async () => {
    const rating = Number(form.rating);
    const sortOrder = Number(form.sortOrder);
    if (!form.name.trim() || form.text.trim().length < 10) { toast.error("Customer name and a meaningful testimonial of at least 10 characters are required."); return; }
    if (!isWholeNumber(rating) || rating < 1 || rating > 5) { toast.error("Rating must be a whole number between 1 and 5."); return; }
    if (!isWholeNumber(sortOrder)) { toast.error("Sort order must be a whole number."); return; }
    if (form.text.trim().length > 1000) { toast.error("Testimonial must be 1,000 characters or fewer."); return; }
    const imageError = validateImageFiles(form.media ? [form.media] : [], { maxFiles: 1 });
    if (imageError) { toast.error(imageError); return; }
    try { setSaving(true); const fd = new FormData(); Object.entries({ ...form, name: form.name.trim(), location: form.location.trim(), text: form.text.trim(), rating, sortOrder }).forEach(([key, value]) => { if (key === "media") { if (value) fd.append("media", value); } else fd.append(key, String(value)); }); const { data } = editingId ? await API.put(`/testimonials/${editingId}`, fd) : await API.post("/testimonials", fd); setItems((current) => editingId ? current.map((item) => item._id === editingId ? data.data : item) : [...current, data.data].sort((a, b) => a.sortOrder - b.sortOrder)); toast.success(data.message || "Testimonial saved."); setEditorOpen(false); } catch (error) { toast.error(getErrorMessage(error, "Testimonial could not be saved.")); } finally { setSaving(false); }
  };
  const archive = async () => { if (!archiveTarget) return; try { setSaving(true); const { data } = await API.delete(`/testimonials/${archiveTarget._id}`); setItems((current) => current.map((item) => item._id === archiveTarget._id ? { ...item, isActive: false } : item)); toast.success(data.message || "Testimonial archived."); setArchiveTarget(null); } catch (error) { toast.error(getErrorMessage(error)); } finally { setSaving(false); } };
  const selectedPreview = useObjectUrl(form.media);
  const preview = selectedPreview || (existingImage ? assetUrl(existingImage) : "");
  return <div className="space-y-6"><PageHeader eyebrow="Social proof" title="Testimonials" description="Publish only genuine, consented customer statements. Testimonials appear on the storefront in sort-order sequence." actions={<><Button variant="secondary" onClick={load}><RefreshCw size={17} /> Refresh</Button><Button onClick={openCreate}><Plus size={17} /> Add testimonial</Button></>} />
    <Card className="overflow-hidden">{loading ? <LoadingState label="Loading testimonials…" /> : items.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item._id} className="border-b border-r border-stone-100 p-5"><div className="flex items-start gap-3">{item.image ? <img src={assetUrl(item.image)} alt="" className="h-12 w-12 rounded-full border object-cover" /> : <div className="grid h-12 w-12 place-items-center rounded-full bg-brand-50 text-brand-700"><Quote size={20} /></div>}<div className="min-w-0"><h2 className="font-bold text-stone-950">{item.name}</h2><p className="text-xs text-stone-500">{item.location || "Location not shown"}</p></div><Badge className="ml-auto" tone={item.isActive !== false ? "success" : "neutral"}>{item.isActive !== false ? "Live" : "Hidden"}</Badge></div><div className="mt-3 flex text-gold-500">{Array.from({ length: Number(item.rating || 5) }, (_, index) => <Star key={index} size={14} fill="currentColor" />)}</div><p className="mt-3 line-clamp-5 text-sm leading-6 text-stone-700">“{item.text}”</p><p className="mt-3 text-xs text-stone-500">Sort order: {item.sortOrder || 0}</p><div className="mt-4 flex justify-end gap-2"><Button size="sm" variant="secondary" onClick={() => openEdit(item)}><Pencil size={15} /> Edit</Button>{item.isActive !== false && <Button size="sm" variant="danger" onClick={() => setArchiveTarget(item)}><Archive size={15} /></Button>}</div></article>)}</div> : <EmptyState icon={Quote} title="No testimonials" description="Add only verified and approved customer feedback." action={<Button onClick={openCreate}><Plus size={17} /> Add testimonial</Button>} />}</Card>
    <Modal open={editorOpen} onClose={() => setEditorOpen(false)} title={editingId ? "Edit testimonial" : "Add testimonial"} size="md" footer={<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditorOpen(false)}>Cancel</Button><Button onClick={submit} disabled={saving}>{saving ? "Saving…" : "Save testimonial"}</Button></div>}><div className="grid gap-5"><Field label="Customer name" required><Input value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></Field><Field label="Location"><Input value={form.location} onChange={(event) => setForm((current) => ({ ...current, location: event.target.value }))} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Rating"><Input type="number" min="1" max="5" value={form.rating} onChange={(event) => setForm((current) => ({ ...current, rating: event.target.value }))} /></Field><Field label="Sort order"><Input type="number" step="1" value={form.sortOrder} onChange={(event) => setForm((current) => ({ ...current, sortOrder: event.target.value }))} /></Field></div><Field label="Testimonial" required><Textarea rows="6" maxLength="1000" value={form.text} onChange={(event) => setForm((current) => ({ ...current, text: event.target.value }))} /></Field><Field label="Customer image"><Input type="file" accept="image/*" onChange={(event) => setForm((current) => ({ ...current, media: event.target.files?.[0] || null }))} /></Field>{preview && <img src={preview} alt="Preview" className="h-28 w-28 rounded-full border object-cover" />}<Toggle checked={form.isActive} onChange={(value) => setForm((current) => ({ ...current, isActive: value }))} label="Visible on storefront" /></div></Modal><ConfirmDialog open={Boolean(archiveTarget)} onClose={() => setArchiveTarget(null)} onConfirm={archive} loading={saving} dangerous title="Archive testimonial" confirmLabel="Archive" description={`Hide the testimonial from ${archiveTarget?.name}?`} />
  </div>;
}
