export const SITE = Object.freeze({
  name: "Legend Killer",
  companyName: "Legend Born Nutrition",
  alternateNames: [
    "Legend Born Nutrition",
    "Legend Born Nutrition Private Limited",
    "LEGEND BORN NUTRITION PRIVATE LIMITED",
    "Legend Killer",
    "The Viper Protocol",
    "Legend Killer Nutrition",
  ],
  tagline: "The Viper Protocol",
  legalEntity: "LEGEND BORN NUTRITION PRIVATE LIMITED",
  url: (import.meta.env.VITE_SITE_URL || "https://legendbornnutrition.com").replace(/\/$/, ""),
  language: "en-IN",
  locale: "en_IN",
  currency: "INR",
  foundingDate: "2024",
  description: "High-performance nutritional protein supplements, whey isolates, pre-workouts, creatine, and anabolic muscle builders engineered for elite athletes by Legend Born Nutrition Private Limited.",
  ogImagePath: "/og-social.jpg",
  ogImageAlt: "Legend Killer by Legend Born Nutrition — High Performance Sports Nutrition & Supplements",
  supportEmail: "support@legendbornnutrition.com",
  supportPhoneDisplay: "+91 98822 92197",
  supportPhoneHref: "+919882292197",
  location: "PROPERTY IDNO.SRS/B04/227, NEAR VIVEKANAND SCHOOL, Sirsa, Haryana, 125055, India",
  registeredAddress: "PROPERTY IDNO.SRS/B04/227, NEAR VIVEKANAND SCHOOL, Sirsa, Sirsa, Sirsa, Haryana, India, 125055",
  address: {
    streetAddress: "PROPERTY IDNO.SRS/B04/227, NEAR VIVEKANAND SCHOOL",
    addressLocality: "Sirsa",
    addressRegion: "Haryana",
    postalCode: "125055",
    addressCountry: "IN",
  },
  businessHours: "Monday to Saturday · 10:00 AM to 7:00 PM",
  socials: {
    instagram: "https://www.instagram.com/legendbornnutrition",
    youtube: "https://www.youtube.com/@legendbornnutrition",
    twitter: "https://twitter.com/legendbornnutr",
    linkedin: "https://www.linkedin.com/company/legendbornnutrition",
    facebook: "https://www.facebook.com/legendbornnutrition",
  },
});
